<?php

namespace Laravel\Telescope\Database\Factories;

use Illuminate\Database\Eloquent\Factories\Factory;
use Laravel\Telescope\EntryType;
use Laravel\Telescope\Storage\AdminModel;

class AdminModelFactory extends Factory
{
    /**
     * Get the name of the model that is generated by the factory.
     *
     * @return string
     */
    public function modelName()
    {
        return AdminModel::class;
    }

    /**
     * {@inheritdoc}
     */
    public function definition()
    {
        return [
            'sequence' => random_int(1, 10000),
            'uuid' => $this->faker->uuid(),
            'email' => $this->faker->email(),
            'password' => '123456',
            'allowed_applications' => [],
        ];
    }
}
